# Generated by Django 3.1.6 on 2021-02-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.IntegerField()),
                ('student_name', models.CharField(max_length=50)),
                ('student_class', models.IntegerField()),
                ('student_address', models.CharField(max_length=200)),
            ],
        ),
    ]
